# Generated by Django 5.0.1 on 2026-02-19 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='竞赛名称')),
                ('description', models.TextField(blank=True, verbose_name='竞赛说明')),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('submission_deadline', models.DateTimeField(verbose_name='作品提交截止时间')),
                ('review_deadline', models.DateTimeField(blank=True, null=True, verbose_name='评审截止时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('open', '开放报名'), ('reviewing', '评审中'), ('closed', '已结束')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '竞赛',
                'verbose_name_plural': '竞赛',
                'db_table': 'contests_contest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='contests_co_status_6c305a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='组别名称')),
                ('description', models.TextField(blank=True, verbose_name='组别说明')),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, verbose_name='最大文件大小(MB)')),
                ('allowed_formats', models.CharField(default='pdf,docx,doc,jpg,jpeg,png', help_text='用逗号分隔，如：pdf,docx,jpg', max_length=200, verbose_name='允许的文件格式')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='contests.contest', verbose_name='所属竞赛')),
            ],
            options={
                'verbose_name': '竞赛组别',
                'verbose_name_plural': '竞赛组别',
                'db_table': 'contests_category',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=200, verbose_name='作品标题')),
                ('work_description', models.TextField(blank=True, verbose_name='作品说明')),
                ('file', models.FileField(upload_to='submissions/%Y/%m/', verbose_name='作品文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size_kb', models.PositiveIntegerField(null=True, verbose_name='文件大小(KB)')),
                ('submission_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='参赛编号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('under_review', '评审中'), ('reviewed', '已评审')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.category', verbose_name='参赛组别')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.contest', verbose_name='所属竞赛')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='参赛选手')),
            ],
            options={
                'verbose_name': '参赛作品',
                'verbose_name_plural': '参赛作品',
                'db_table': 'contests_submission',
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['contest'], name='contests_ca_contest_3fe9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['contestant'], name='contests_su_contest_06eb09_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='contests_su_status_f74a58_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submission_number'], name='contests_su_submiss_f47c4a_idx'),
        ),
    ]
