# Generated by Django 5.0.1 on 2026-02-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='正文内容')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/covers/%Y/%m/', verbose_name='封面图片')),
                ('category', models.CharField(choices=[('news', '中心动态'), ('event', '活动通知'), ('achievement', '学术成果')], db_index=True, default='news', max_length=20, verbose_name='分类')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '新闻文章',
                'verbose_name_plural': '新闻文章',
                'db_table': 'news_article',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
