# Generated by Django 5.0.1 on 2026-02-19 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-publish_date'], name='news_articl_publish_345e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='news_articl_categor_5c78fc_idx'),
        ),
    ]
