# Generated by Django 5.0.1 on 2026-02-19 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成评审')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to=settings.AUTH_USER_MODEL, verbose_name='评委')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='contests.submission', verbose_name='参赛作品')),
            ],
            options={
                'verbose_name': '评审分配',
                'verbose_name_plural': '评审分配',
                'db_table': 'reviews_assignment',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='评审意见')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='总分')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.assignment', verbose_name='评审分配')),
            ],
            options={
                'verbose_name': '评审意见',
                'verbose_name_plural': '评审意见',
                'db_table': 'reviews_review',
            },
        ),
        migrations.CreateModel(
            name='ScoreDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='维度名称')),
                ('description', models.TextField(blank=True, verbose_name='维度说明')),
                ('max_score', models.PositiveIntegerField(help_text='该维度的最高分数', verbose_name='满分')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='计算总分时的权重系数', max_digits=3, verbose_name='权重')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_dimensions', to='contests.contest', verbose_name='所属竞赛')),
            ],
            options={
                'verbose_name': '评分维度',
                'verbose_name_plural': '评分维度',
                'db_table': 'reviews_scoredimension',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='分数')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='reviews.assignment', verbose_name='评审分配')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='reviews.scoredimension', verbose_name='评分维度')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
                'db_table': 'reviews_score',
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['judge'], name='reviews_ass_judge_i_32dcee_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['submission'], name='reviews_ass_submiss_ad6e5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('submission', 'judge')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['assignment'], name='reviews_rev_assignm_49a7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='scoredimension',
            index=models.Index(fields=['contest'], name='reviews_sco_contest_512089_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['assignment'], name='reviews_sco_assignm_62c9df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('assignment', 'dimension')},
        ),
    ]
